version: "3.9"

services:
  whatsapp_webhook:
    build: .                # ← agora compila a imagem a partir do Dockerfile
    environment:
      - VERIFY_TOKEN=9f6c4e1c-bb1a-47fa-a784-3b8b5d2d2a5e
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webhook.rule=Host(`webhook.vextrum.site`)"
      - "traefik.http.routers.webhook.entrypoints=websecure"
      - "traefik.http.routers.webhook.tls=true"
      - "traefik.http.services.webhook.loadbalancer.server.port=3000"
