version: "3.9"

services:
  whatsapp_webhook:
    image: node:20-alpine          # vamos instalar dependências na inicialização
    command: sh -c "npm install --omit=dev && node index.js"
    working_dir: /app
    volumes:
      - ./:/app                    # monta o código do repo dentro do container
    environment:
      - VERIFY_TOKEN=MinhaSenhaWebhook123
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webhook.rule=Host(`webhook.vextrum.site`)"
      - "traefik.http.routers.webhook.entrypoints=websecure"
      - "traefik.http.routers.webhook.tls=true"
      - "traefik.http.services.webhook.loadbalancer.server.port=3000"
