version: "3.9"

services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks: [proxy]

  whatsapp_webhook:
    build: .
    container_name: whatsapp_webhook
    restart: unless-stopped
    environment:
      - VERIFY_TOKEN=TroquePorAlgoUnico
    networks: [proxy]

networks:
  proxy:

volumes:
  caddy_data:
  caddy_config:
